#██████╗ ██╗   ██╗     ██████╗ █████╗ ████████╗ █████╗ ██████╗ ███╗   ███╗██╗██████╗ ███████╗██████╗
#██╔══██╗╚██╗ ██╔╝    ██╔════╝██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗████╗ ████║██║██╔══██╗██╔════╝██╔══██╗
#██████╔╝ ╚████╔╝     ██║     ███████║   ██║   ███████║██║  ██║██╔████╔██║██║██████╔╝█████╗  ██████╔╝
#██╔══██╗  ╚██╔╝      ██║     ██╔══██║   ██║   ██╔══██║██║  ██║██║╚██╔╝██║██║██╔══██╗██╔══╝  ██╔══██╗
#██████╔╝   ██║       ╚██████╗██║  ██║   ██║   ██║  ██║██████╔╝██║ ╚═╝ ██║██║██║  ██║███████╗██║  ██║
#╚═════╝    ╚═╝        ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚═╝     ╚═╝╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#
# ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗    ██╗   ██╗███╗   ███╗██╗
#██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝    ╚██╗ ██╔╝████╗ ████║██║
#██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗    ╚████╔╝ ██╔████╔██║██║
#██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║     ╚██╔╝  ██║╚██╔╝██║██║
#╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝██╗   ██║   ██║ ╚═╝ ██║███████╗
# ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ ╚═╝   ╚═╝   ╚═╝     ╚═╝╚══════╝

allow_infinite_effects: false

ritual_duration: 600  # Duration in seconds (10 minutes)
ritual_duration_ender: 3600 # Duration in seconds (1hr)

brewing_particles: true

empty_effect_icon: true

player_head_drops: true

enable_discord_broadcasts: false

discord_webhook_url: ""

invis_deaths: false # Change death messages in messages.yml (WILL ONLY APPLY TO INVIS ONES), made by Duckiee2

brewing_gui: true

effect_drops: Random

# Random = Random effect drops
# 1/2 = Slot 1/2 Drops
# None = None drop

join_effects_enabled: false

join_effects: # Same Names from messages.yml
  - ocean
  - emerald
  - fire
  - speed

craft_limits:
  emerald:
    augmented_limit: 1
    regular_limit: 3
  feather:
    augmented_limit: 1
    regular_limit: 3
  fire:
    augmented_limit: 1
    regular_limit: 3
  end_first:
    augmented_limit: 1 # Augmented End Recipe
    regular_limit: 0
  end_second:
    augmented_limit: 0
    regular_limit: 3 # Regular End Recipe
  frost:
    augmented_limit: 1
    regular_limit: 3
  haste:
    augmented_limit: 1
    regular_limit: 3
  heart:
    augmented_limit: 1
    regular_limit: 3
  invis:
    augmented_limit: 1
    regular_limit: 3
  ocean:
    augmented_limit: 1
    regular_limit: 3
  regen:
    augmented_limit: 1
    regular_limit: 3
  speed:
    augmented_limit: 1
    regular_limit: 3
  strength:
    augmented_limit: 1
    regular_limit: 3
  thunder:
    augmented_limit: 1
    regular_limit: 3
  apophis:
    augmented_limit: 1
    regular_limit: 3
  thief:
    augmented_limit: 1
    regular_limit: 3
# Cooldown is Duration + Cooldown

invisibility:
  cooldown:
    default: 121
    augmented: 61
  duration:
    default: 20
    augmented: 25

apophis:
  cooldown:
    default: 125
    augmented: 75
  duration:
    default: 15
    augmented: 18

emerald:
  cooldown:
    default: 91
    augmented: 76
  duration:
    default: 30
    augmented: 35

ender:
  cooldown:
    default: 60
    augmented: 50
  duration:
    default: 15
    augmented: 20

feather:
  cooldown:
    default: 63
    augmented: 33
  duration:
    default: 2
    augmented: 2

fire:
  cooldown:
    default: 66
    augmented: 36
  duration:
    default: 5
    augmented: 6

frost:
  cooldown:
    default: 121
    augmented: 76
  duration:
    default: 15
    augmented: 20

haste:
  cooldown:
    default: 76
    augmented: 46
  duration:
    default: 15
    augmented: 20

heart:
  cooldown:
    default: 181
    augmented: 91
  duration:
    default: 60
    augmented: 80

ocean:
  cooldown:
    default: 76
    augmented: 46
  duration:
    default: 15
    augmented: 20

regen:
  cooldown:
    default: 91
    augmented: 61
  duration:
    default: 15
    augmented: 30

speed:
  dashMultiplier: 20
  playerVelocityMultiplier: 2
  cooldown:
    default: 21
    augmented: 11
  duration:
    default: 1
    augmented: 1

strength:
  cooldown:
    default: 91
    augmented: 61
  duration:
    default: 15
    augmented: 20


thunder:
  cooldown:
    default: 81
    augmented: 51
  duration:
    default: 10
    augmented: 10


thief:
  cooldown:
    default: 300
    augmented: 150


ocean_pulling:
  pull:
    interval: 20 # In ticks (20 ticks = 1 second)
    radius: 5
    strength: 0.3


extra_effects:
  Apophis: false
  Thief: false