[versions]
placeholderapi = "2.12.3"
worldguard = "7.0.17"
run-paper = "3.0.2"
paperweight = "2.0.0-beta.21"
guava = "33.6.0-jre!!"
gson = "2.14.0!!"
slf4j = "1.7.30"
log4j = "2.14.0"
shadow = "9.6.1"
jetbrains-annotations = "26.0.2-1"
adventure = "5.2.0"
snakeyaml = "2.6"

[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
log4j = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
